apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:ocBLlKyHkRzTheCcNNroM3XdwDff0Q7CsoGFVdAG/ayJy0qgjzVt1Q==,iv:wOHwbQnKGDRCUgrCwAHkhroFYYv7zYe1SGy5zFD0bcM=,tag:7PCER94EdHed22GoEqLeWw==,type:str]
sops:
  age:
    - recipient: age1ufm6gx9x9rnktd4wwqy2jwsd4kn3yl0kjkdxmgn3rlzh6e9l5sksu4xhzu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSFY3M3JVNnRoQWkrZ0F3
        S0F0WXUvdmR1V2xiOGVSbnBRUVgvZm5nNTBrCndCT0tKSlJuYTliK2ZDelNHK0ho
        amhrN3NINlJQeHdGdWl3ZTUvYnNCdlEKLS0tIDdaWjl4UkNSTldBSElLTHlmM3Ji
        Ny9zaXRBQURZUmEwbCtrTmtJMDUrTG8KgKn1xNI5gnMvnhvVJEUP2yU3z5RXuHoT
        H1HruJcTeYblXZM+yrECxDgEeTvQo76NrSfzYdGdA/9dFs7jv0RjZA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-08T22:32:01Z"
  mac: ENC[AES256_GCM,data:SchtL8ezMRrRS8y00i1kTUXN7+Js10NFy47pGMDtgKghJPN5t5PnHJ9acAGB5iGXoo1WcCTwYALRj9vh5euuuf8kna2qhO09nALXeIi5WeYgDCv8BFDlorCkp1ANvZfG8Y9cXe9Qxr7XNf4/4a2N1FmbZ0+GyUmNRTmP5Z0khE4=,iv:nYfFZt4kDEQJAXGGaU7qd2kEKFbIpjudQUywRGqVMGM=,tag:kH00N82zX7ek/z7VO2fi/g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
