apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:8yFR4oW7JRItA8g=,iv:i2ZOvnFAHuJ9mFd15rZ8yvD+L8qVphfmfOA9J4/JCv0=,tag:A6AKJ2rZk3TThEjtci4Otw==,type:str]
    IPAM_IP_SATISFACTORY: ENC[AES256_GCM,data:HKqaKWI/X33wifo=,iv:Vuf1lyvTPf5qTYimNKW3briiSd2z5E4TFZKJ2mwEUEc=,tag:XzGwsFXjW8SIImE5aADCZQ==,type:str]
sops:
    age:
        - recipient: age1ufm6gx9x9rnktd4wwqy2jwsd4kn3yl0kjkdxmgn3rlzh6e9l5sksu4xhzu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByd1hVQjRwMThKekxGbVVJ
            UFJnZmlSNGR6a3VqRWI1dmxWMS9pYXBxakVrCk9uNENQcDhsaGVHcjRVWjBQV3RL
            SmhOejRINGdEd1lhd1Y0aytSMXhDNGcKLS0tIGV4M2ZUY3dZbWxrRG5rZzZkenNR
            ci9DVE9zTHg3UU9uYkVacmZyOG9sNzQKtfC0lZN5gJS17xdHVVx71xCffrokY3OT
            Kk72SaSG4Mtjm8xxzwsvwNZUgtMrGYiymgabBK1CW/SEZZKrWpAafA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T04:16:28Z"
    mac: ENC[AES256_GCM,data:KY5o8gxkg1Bww6lnwcOvFajI+Kqut56rH2ZD9YzmuCjK5zaRW1632Y2EgTZ9FAba/EUFXodOeR30XXPzy30KPUflRPf/Y+8eYuJSi6i2Ie3XEwuq8X85xNle1RQVU9t+tB7WwFqtHEZfZqQHME6/74gv2QXhHY7njzBbsdWOKCI=,iv:BXQ8QHTITbmvRUSm+YVVeWZYWozSSuOWUPMzVsh+w0k=,tag:eb8eI8fdI/pAUMQO2ELvYg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
