apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:6QjsLIZzlqaTp14+asnqMZuNZSqOVIA1WXcrd5YL1us=,iv:I0bjK/x2K8d2Yn5WfD4wo8j0pGhlkByVR1uGu2reZqs=,tag:n5TbbNDU6JHbI1Sz85ghpw==,type:str]
sops:
  age:
    - recipient: age1ufm6gx9x9rnktd4wwqy2jwsd4kn3yl0kjkdxmgn3rlzh6e9l5sksu4xhzu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYT3NzVEZqdzQySUdqalVn
        U1JkcmVOSFk0R0pvcHBMaC9nOHVhRmFSNVhjCnFBaXhSMnhOeDdOdFpYRU1mUFJW
        KzY2YWlYczNtWHZzQkUwWU9rWlh0TVUKLS0tIElxZzVZenVaRGw3TFAwZ2F4Vmdl
        V2JQaWZyR3drYi81Sm01SFhPQWtJczgKZA1AkKSWKSJLnVrV6a3rv6Vq28Gh5PoS
        8InMFsXtvpWuHHzWrAIXXvlS5j6CC0yKSpFOrzOGya4X2tRhl8Wp6A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-08T22:32:01Z"
  mac: ENC[AES256_GCM,data:n7632tVDPQLhtFY8W2IJCS70HNjC0jgsAsksbJbNrdK9ZtsfbzTvB3cCWTM3RPzWVQXAVnCizqnlOuzhBrQYFmQP96OQ5PolGTjrCkf8SXGtSY+8D5ReGfXk2salVB63YPmnYn892KlzYCix/nC3u4MtYXAaWqfzYM49kG1boLE=,iv:SDWYALW1+nciD3EbAvErh1uIgTu8ITDDu8Se9kY6LKc=,tag:IdZTUyhkacS2RgzYF7ZKyQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
