apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:drXdnruFAvdbto5qdJxIVebRnmLPdeW8YvdT/clGq4I5Lt9ECKoddJqq5v8SvD3o0MGiFufwCDX2VaetjF5tGn7Jq7dFOoJdxG11q59LUzst7+AXZjuxVges1OGYQRMCP+Bzi80pt20nMEMtOl7MYCvVW3qwgnMU+w1PB683hIqSp2saaCDApALkgKP8tjpssNG04Yw8OY8qIN4RH8mnfeF/x2EAzvINtLfjNAzvMgECC3ID,iv:RO/fjcIhscNA54RGH8NH4XZHifwAlXFY8/C3WPWvzRU=,tag:ChYV1k5Cd1AaKwfkm12XFQ==,type:str]
sops:
  age:
    - recipient: age1ufm6gx9x9rnktd4wwqy2jwsd4kn3yl0kjkdxmgn3rlzh6e9l5sksu4xhzu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZWdGT2hrd0VXZWZEQmlz
        bEtHOWZzR2hUa0JDMERXNXhYckwyZFYrekRVCmJLQTczSm1zWm13MGVXQm5LaVV3
        eDZqZGFhcExsMFJNZlBVR0xDaXpkOXMKLS0tIEZKeUprWkhCOGJmZlkzQTVoSHhS
        TWdQSDFVeUJCVzVLTnBnZ1RpelNaaDAKMoB+034ukk58be3+6kkLHrNz6S9jf3q4
        AKVKm32KK0Hdk//FFkoX4xmbktGEG82PFhjiSbArJUxTFVyEW1R9TQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-08T22:32:01Z"
  mac: ENC[AES256_GCM,data:V03yXSxx68+PSb6gjQIQm5kwv1Kg0Tsj/suzOn8HNZlJjoCCLCM+KyWkGNGYGMd61HVdwgY6OEswoyQE39HPCBtPwidd+czwVk1p4NLJ5YdZ8dmqcNIHFo7iEDDgs+G0wDsoLCg7wSg/zq2/Hwa5A1+kZb4xIuaLvBMQKX04GT8=,iv:YO6RHeEMnK2YtrNyncB0dJ7cm3140jGHl7rHMEwPyTg=,tag:jYUdnOFTtI6cEgVpThqJbw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
