apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:OCIoS6WmmmpNZPANWq36GRzBHNXL3jjwXm6qKwD9UQCTMOR3TS6ujQ==,iv:I02uMPvKA/Z2ThpNc3yLztkujss1Fu3rzfN7Km+WH+c=,tag:VjWJEy++D8ZQ/vBfUxJHLg==,type:str]
sops:
  age:
    - recipient: age1ufm6gx9x9rnktd4wwqy2jwsd4kn3yl0kjkdxmgn3rlzh6e9l5sksu4xhzu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWk1NczBoTDQyOWh2VmNs
        UWNIUkRYZWF5NFFqa2xyRUlaTkloTkp6ZEFRCmVTOWEweFl0Sm5OeXpKZE9pbE9q
        NlFrVGgvZGgwNm1wSnlPUUlxbHdqc2MKLS0tIGRqcGZ3MUZKSFhZbVZBZUpZaWxE
        YVZncmtIMmVtQzFsWk0xUFV5ZStYSDQKWvD3NUMf/SykSxx7QpdgObaPhjFx/Oj3
        AWiOV8zTAFhocJtRQtrrydaO1XVeD1oyea623dBDFE58JR7DtU1VNA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-08T22:32:01Z"
  mac: ENC[AES256_GCM,data:udicf9xHedol1XYKo3xOy0TFHLfJ7dPtBfz0sm+DvO1iIciB/gYt/Bamvk+DQUHTYw5zRAmkMPSvFp0fol4Ly0f1l7J40AGDzgl36AZ7Ygblf9KDo7mB0outR5dMGje7lSJlPy2cZQBtXboUh9CwdTib0fyQWtBkY0rcpaeVugs=,iv:NuJpcEa4DncW9gJT0gw6fglmrH0CMaTwfDYbEB6bTZE=,tag:U9G9F7n7Qt5OyyH3lsdJIw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
